name: Uwazi CI

on:
  push:
    branches:
      - test_deploy

jobs:
  delploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.21.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.21.x'
      - name: Cache node modules
        uses: actions/cache@v1.1.2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - run: yarn production-build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "prod/"
            REMOTE_HOST: ${{ secrets.DEPLOY_SERVER }}
            REMOTE_USER: ${{ secrets.DEPLOY_USER }}
            TARGET: uwazi_deployment
