name: Snyk

on: [push]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: yarn add lodash
      # - name: Run Snyk to check for vulnerabilities
      #   uses: snyk/actions/node@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Get yarn global bin directory
        id: yarn-bin
        run: echo "::set-output name=dir::$(yarn global bin)"
      - run: yarn global add lodash
      - run: yarn global add snyk
      - run: ${{ steps.yarn-bin.outputs.dir }}/snyk auth ${{ secrets.SNYK_TOKEN }}
      - run: ${{ steps.yarn-bin.outputs.dir }}/snyk test
